version: '3.5'

services:

  mysql:
    image: spec-mysql
    build:
      context: .
      dockerfile: .docker/images/mysql/dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    restart: always
    env_file:
      - .env_docker
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./spec_dev_data/spec_mysql_data:/var/lib/mysql"
    networks:
      - spec_network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    env_file:
      - .env_docker
    networks:
      - spec_network

  flask:
    image: spec-flask
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    hostname: flask
    restart: always
    env_file:
      - .env_docker
    depends_on:
      - mysql
    ports:
      - 5050:5050
    volumes:
      - .:/app
      - "./spec_dev_data/avatars:/app/data/avatars"
      - "./spec_dev_data/db:/app/data/db"
      - "./spec_dev_data/log:/app/data/log"
    networks:
      - spec_network

  background:
    image: spec-background
    build:
      context: .
      dockerfile: .docker/images/background/dockerfile-background
    hostname: background
    restart: always
    env_file:
      - .env_docker
    depends_on:
      - mysql
    volumes:
      - .:/app
      - "./spec_dev_data/db:/app/data/db"
      - "./spec_dev_data/log:/app/data/log"
    networks:
      - spec_network

  registry:
    restart: on-failure
    hostname: registry
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=https://localhost:5050/token_auth
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="Auth service"
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/mnt/local/certs/domain.crt
      - REGISTRY_HTTP_TLS_CERTIFICATE=/mnt/local/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/mnt/local/certs/domain.key
    volumes:
      - "./spec_dev_data/registry_auth/data:/mnt/registry/data"
      - "./spec_dev_data/registry_auth/certs:/mnt/local/certs"
    networks:
      - spec_network

networks:
  spec_network:
