version: '3.5'

services:

  mysql:
    image: spec-mysql
    build:
      context: .
      dockerfile: .docker/images/mysql/dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    restart: always
    env_file:
      - .env_dev
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./spec_dev_data/spec_mysql_data:/var/lib/mysql"
    networks:
      - spec_network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    env_file:
      - .env_dev
    networks:
      - spec_network

  flask:
    image: spec-flask
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    hostname: flask
    restart: always
    env_file:
      - .env_dev
    depends_on:
      - mysql
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - spec_network
    entrypoint:
      - /app/scripts/entry_point.sh

networks:
  spec_network:
