FROM python:3.8

RUN pip install --upgrade pip

# create non-root user
RUN adduser --disabled-password spectacles

# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app

# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $APP
# set permissions to non-root user
RUN chown -R spectacles:spectacles $APP

WORKDIR $APP

USER spectacles

ENV PATH="/home/spectacles/.local/bin:${PATH}"

# Copy the current directory contents into the container at /app
COPY --chown=spectacles:spectacles . $APP

RUN pip install -r requirements.txt

RUN mv /app/client_secrets_template.json /app/client_secrets.json

RUN rm -rf /app/.docker

ENTRYPOINT ["flask"]

CMD ["runserver"]

EXPOSE 5050
