FROM python:3.8

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

COPY ./.docker/files/background/install.sh .

RUN sed -i -e 's/\r$//' ./install.sh

RUN ./install.sh

RUN rm ./install.sh

ENTRYPOINT ["python"]

CMD ["manager.py", "runbackground"]
